"""Architectural guards."""

import ast
import pathlib
import re
import sys

import pytest

RUNTIME = pathlib.Path(__file__).resolve().parent.parent / "rainalert"


def test_runtime_never_imports_wradlib():
    """wradlib is the test oracle, not a runtime dependency (D-21).

    It drags in a large scientific stack that would slow every cold start of a job that runs 288
    times a day, and the whole point of the hand-written decoder is to avoid it.
    """
    offenders = []
    for path in RUNTIME.rglob("*.py"):
        tree = ast.parse(path.read_text(), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                names = [node.module or ""]
            else:
                continue
            if any(name.split(".")[0] == "wradlib" for name in names):
                offenders.append(f"{path.relative_to(RUNTIME).as_posix()}:{node.lineno}")
    # Mentioning wradlib in a docstring is fine and in fact wanted; importing it is not.
    assert offenders == []


def test_multi_cycle_archive_is_rejected_by_read_cycle(outage_cycles):
    """Merging cycles yields duplicate leads - a plausible-looking wrong answer."""
    from rainalert.radar.decoder import RVFormatError, read_cycle

    with pytest.raises(RVFormatError, match="4 cycles"):
        read_cycle(outage_cycles)


def test_migrations_match_the_models(postgres_url, monkeypatch):
    """Alembic and the ORM must not drift: a model change without a migration is a broken deploy."""
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected

    monkeypatch.setenv("DATABASE_URL", postgres_url)
    from rainalert.config import get_settings

    get_settings.cache_clear()

    # Start from an empty schema: other tests create and drop tables directly, which would leave
    # alembic_version claiming "head" over a database that no longer matches it.
    from sqlalchemy import create_engine, text

    engine = create_engine(postgres_url)
    with engine.begin() as conn:
        conn.execute(text("DROP SCHEMA public CASCADE"))
        conn.execute(text("CREATE SCHEMA public"))
    engine.dispose()

    root = pathlib.Path(__file__).resolve().parent.parent
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "migrations"))
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only on drift
        pytest.fail(f"models and migrations have drifted: {exc}")
    finally:
        get_settings.cache_clear()


def test_every_runtime_import_is_a_declared_dependency():
    """The container installs from pyproject alone, so an undeclared import is a crash at runtime.

    Regression: Pillow was used by the overlay renderer and never declared. The local venv had it
    from a manual install, so every test passed while the image would have built cleanly and then
    died on first render.
    """
    import tomllib

    root = pathlib.Path(__file__).resolve().parent.parent
    declared = tomllib.loads((root / "pyproject.toml").read_text())["project"]["dependencies"]

    def normalise(name: str) -> str:
        # PEP 503: distribution names treat -, _ and . as equivalent, so pydantic_settings the
        # import and pydantic-settings the distribution are the same thing.
        return re.sub(r"[-_.]+", "-", name).lower()

    names = {
        normalise(d.split("[")[0].split(">")[0].split("=")[0].split("<")[0].strip())
        for d in declared
    }
    # Import name -> distribution name, where they differ.
    aliases = {
        "pil": "pillow",
        "psycopg": "psycopg",
        "yaml": "pyyaml",
        "dateutil": "python-dateutil",
    }
    stdlib = set(sys.stdlib_module_names)

    third_party: set[str] = set()
    for path in RUNTIME.rglob("*.py"):
        for node in ast.walk(ast.parse(path.read_text(), filename=str(path))):
            if isinstance(node, ast.Import):
                mods = [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                mods = [node.module or ""] if node.level == 0 else []
            else:
                continue
            for mod in mods:
                top = mod.split(".")[0].lower()
                if top and top not in stdlib and top != "rainalert":
                    third_party.add(normalise(aliases.get(top, top)))

    missing = sorted(
        name
        for name in third_party
        # google-cloud-storage is imported lazily inside the GCS adapters and is an optional extra.
        if name not in names and name not in {"google", "wradlib"}
    )
    assert missing == [], f"imported but not declared in pyproject: {missing}"


def test_the_image_installs_the_extras_its_lazy_imports_need():
    """The exemption above is only safe if the production image installs that extra.

    It did not. `pip install .` takes the dependency list and none of the extras, so the image
    built cleanly, started cleanly, and died the moment OVERLAY_BUCKET was set - `create_app`
    constructs GCSOverlayStore, whose lazy `from google.cloud import storage` then raises. Cloud
    Run reports that as "the container failed the configured startup probe checks", which names
    neither the import nor the package.
    """
    import tomllib

    root = pathlib.Path(__file__).resolve().parent.parent
    extras = tomllib.loads((root / "pyproject.toml").read_text())["project"].get(
        "optional-dependencies", {}
    )
    assert "gcs" in extras, "the gcs extra moved; this guard needs updating with it"

    install = [
        line
        for line in (root / "Dockerfile").read_text().splitlines()
        if "pip install" in line and not line.lstrip().startswith("#")
    ]
    assert install, "no pip install in the Dockerfile"
    # Every extra the runtime reaches for lazily has to be in the image, or it is only a crash
    # deferred to whichever environment sets the variable that takes that code path.
    assert any("[gcs]" in line for line in install), (
        f"the image does not install the gcs extra: {install}"
    )


# --- local reset -----------------------------------------------------------------------------


@pytest.mark.parametrize(
    "url",
    [
        "postgresql+psycopg://user:pw@db.example.com/rainalert",
        "postgresql+psycopg://user@10.0.0.5:5432/rainalert",
        "postgresql+psycopg://user@rainalert-prod.internal/rainalert",
    ],
)
def test_reset_refuses_a_remote_database(url):
    """The only thing between "reset my test data" and a very bad afternoon."""
    from rainalert.jobs.reset import NotLocal, assert_local

    with pytest.raises(NotLocal):
        assert_local(url)


@pytest.mark.parametrize(
    "url",
    [
        "postgresql+psycopg://user@localhost:5432/rainalert",
        "postgresql+psycopg://user@127.0.0.1/rainalert",
        "postgresql+psycopg://user@/rainalert?host=/tmp",  # unix socket, as Homebrew uses
    ],
)
def test_reset_allows_a_local_database(url):
    from rainalert.jobs.reset import assert_local

    assert_local(url)


def test_reset_keeps_radar_data_by_default(db, tmp_path):
    """Radar cycles cost a request each to rebuild; subscriptions cost a click."""
    from datetime import UTC, datetime

    from rainalert.db.models import CycleStatus, RadarCycle, Subscriber
    from rainalert.jobs.reset import reset
    from rainalert.tokens import hash_address

    with db() as session:
        session.add(
            RadarCycle(
                nominal_time=datetime(2026, 9, 16, 14, 0, tzinfo=UTC),
                fetched_at=datetime(2026, 9, 16, 14, 0, tzinfo=UTC),
                source_url="t",
                sha256=b"\x00" * 32,
                bytes=1,
                frame_count=25,
                status=CycleStatus.OK,
            )
        )
        session.add(
            Subscriber(
                address="a@example.com",
                address_hash=hash_address("email", "a@example.com"),
                created_at=datetime(2026, 9, 16, tzinfo=UTC),
            )
        )
        session.commit()
        engine = session.get_bind()

    outbox = tmp_path / "outbox"
    outbox.mkdir()
    (outbox / "a.eml").write_text("x")

    report = reset(engine, (outbox,))
    assert report.radar_kept is True
    assert not outbox.exists()

    with db() as session:
        assert session.query(Subscriber).count() == 0
        assert session.query(RadarCycle).count() == 1  # kept

    reset(engine, (), keep_radar=False)
    with db() as session:
        assert session.query(RadarCycle).count() == 0


def test_the_web_tier_can_read_the_tables_the_migrations_create(postgres_url, monkeypatch):
    """Two roles by design (F-6), and nothing was granting the second one anything.

    The ingest role owns the schema; the web tier only reads and writes rows. Postgres does not
    share ownership, so every table belonged to the migration runner and the API's first query
    answered 500 with "permission denied for table radar_cycles" - past a healthy container, a
    working ingest job and a `/readyz` that could not say so because its own probe reads
    `alembic_version` and hit the same wall.

    Runs the real migrations against a real second role, because that is the only place the
    grant exists.
    """
    from alembic import command
    from alembic.config import Config
    from sqlalchemy import create_engine, text

    monkeypatch.setenv("DATABASE_URL", postgres_url)
    from rainalert.config import get_settings

    get_settings.cache_clear()

    engine = create_engine(postgres_url)
    try:
        with engine.begin() as conn:
            conn.execute(text("DROP SCHEMA public CASCADE"))
            conn.execute(text("CREATE SCHEMA public"))
            # The role the grant names. Terraform creates it (infra/main.tf); here it has to
            # exist before the migration runs, exactly as it does in production.
            conn.execute(
                text("""
                DO $$ BEGIN
                  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rainalert_api') THEN
                    CREATE ROLE rainalert_api LOGIN PASSWORD 'test-only';
                  END IF;
                END $$;
                """)
            )

        root = pathlib.Path(__file__).resolve().parent.parent
        config = Config(str(root / "alembic.ini"))
        config.set_main_option("script_location", str(root / "migrations"))
        command.upgrade(config, "head")

        with engine.connect() as conn:
            # SET ROLE is how this asks the question without a second connection: privileges are
            # evaluated for the assumed role, which is what the web tier connects as.
            conn.execute(text("SET ROLE rainalert_api"))
            for table in ("radar_cycles", "subscribers", "subscriptions", "alembic_version"):
                # A bare execute is the assertion: without the grant this raises
                # InsufficientPrivilege, which is precisely the production failure.
                conn.execute(text(f"SELECT 1 FROM {table} LIMIT 1"))
            conn.execute(text("RESET ROLE"))

            # The half that keeps it fixed: a table created after the grant must be readable
            # too, or the next migration reintroduces this one deploy later.
            conn.execute(text("CREATE TABLE later_migration_table (id int)"))
            conn.execute(text("SET ROLE rainalert_api"))
            conn.execute(text("SELECT 1 FROM later_migration_table LIMIT 1"))
            conn.execute(text("RESET ROLE"))
            conn.execute(text("DROP TABLE later_migration_table"))
    finally:
        engine.dispose()
        get_settings.cache_clear()


def test_a_permission_error_is_not_reported_as_a_missing_schema(postgres_url, monkeypatch):
    """The readiness probe used to say "the database has no schema yet" when the schema was
    present, current, and merely unreadable by the role asking. That sentence names a cause and
    a fix, and both were wrong - it sent you to re-run migrations that had already run."""
    from alembic import command
    from alembic.config import Config
    from sqlalchemy import create_engine, text
    from sqlalchemy.orm import Session as OrmSession

    from rainalert.db.schema import schema_complaint

    monkeypatch.setenv("DATABASE_URL", postgres_url)
    from rainalert.config import get_settings

    get_settings.cache_clear()

    engine = create_engine(postgres_url)
    try:
        with engine.begin() as conn:
            conn.execute(text("DROP SCHEMA public CASCADE"))
            conn.execute(text("CREATE SCHEMA public"))
            conn.execute(
                text("""
                DO $$ BEGIN
                  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rainalert_nogrant') THEN
                    CREATE ROLE rainalert_nogrant LOGIN PASSWORD 'test-only';
                  END IF;
                END $$;
                """)
            )
            conn.execute(text("GRANT USAGE ON SCHEMA public TO rainalert_nogrant"))

        root = pathlib.Path(__file__).resolve().parent.parent
        config = Config(str(root / "alembic.ini"))
        config.set_main_option("script_location", str(root / "migrations"))
        command.upgrade(config, "head")

        with engine.connect() as conn, OrmSession(bind=conn) as session:
            # A role the grant migration does not name: the schema is there, it just cannot see
            # it - which is exactly the production shape.
            session.execute(text("SET ROLE rainalert_nogrant"))
            complaint = schema_complaint(session)
            session.rollback()
            session.execute(text("RESET ROLE"))

        assert complaint is not None
        assert "cannot read it" in complaint
        assert "no schema yet" not in complaint
    finally:
        engine.dispose()
        get_settings.cache_clear()
