"""Architectural guards."""

import ast
import pathlib
import re
import sys

import pytest

RUNTIME = pathlib.Path(__file__).resolve().parent.parent / "rainalert"


def test_runtime_never_imports_wradlib():
    """wradlib is the test oracle, not a runtime dependency (D-21).

    It drags in a large scientific stack that would slow every cold start of a job that runs 288
    times a day, and the whole point of the hand-written decoder is to avoid it.
    """
    offenders = []
    for path in RUNTIME.rglob("*.py"):
        tree = ast.parse(path.read_text(), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                names = [node.module or ""]
            else:
                continue
            if any(name.split(".")[0] == "wradlib" for name in names):
                offenders.append(f"{path.relative_to(RUNTIME).as_posix()}:{node.lineno}")
    # Mentioning wradlib in a docstring is fine and in fact wanted; importing it is not.
    assert offenders == []


def test_multi_cycle_archive_is_rejected_by_read_cycle(outage_cycles):
    """Merging cycles yields duplicate leads - a plausible-looking wrong answer."""
    from rainalert.radar.decoder import RVFormatError, read_cycle

    with pytest.raises(RVFormatError, match="4 cycles"):
        read_cycle(outage_cycles)


def test_migrations_match_the_models(postgres_url, monkeypatch):
    """Alembic and the ORM must not drift: a model change without a migration is a broken deploy."""
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected

    monkeypatch.setenv("DATABASE_URL", postgres_url)
    from rainalert.config import get_settings

    get_settings.cache_clear()

    # Start from an empty schema: other tests create and drop tables directly, which would leave
    # alembic_version claiming "head" over a database that no longer matches it.
    from sqlalchemy import create_engine, text

    engine = create_engine(postgres_url)
    with engine.begin() as conn:
        conn.execute(text("DROP SCHEMA public CASCADE"))
        conn.execute(text("CREATE SCHEMA public"))
    engine.dispose()

    root = pathlib.Path(__file__).resolve().parent.parent
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "migrations"))
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only on drift
        pytest.fail(f"models and migrations have drifted: {exc}")
    finally:
        get_settings.cache_clear()


def test_every_runtime_import_is_a_declared_dependency():
    """The container installs from pyproject alone, so an undeclared import is a crash at runtime.

    Regression: Pillow was used by the overlay renderer and never declared. The local venv had it
    from a manual install, so every test passed while the image would have built cleanly and then
    died on first render.
    """
    import tomllib

    root = pathlib.Path(__file__).resolve().parent.parent
    declared = tomllib.loads((root / "pyproject.toml").read_text())["project"]["dependencies"]
    def normalise(name: str) -> str:
        # PEP 503: distribution names treat -, _ and . as equivalent, so pydantic_settings the
        # import and pydantic-settings the distribution are the same thing.
        return re.sub(r"[-_.]+", "-", name).lower()

    names = {
        normalise(d.split("[")[0].split(">")[0].split("=")[0].split("<")[0].strip())
        for d in declared
    }
    # Import name -> distribution name, where they differ.
    aliases = {
        "pil": "pillow",
        "psycopg": "psycopg",
        "yaml": "pyyaml",
        "dateutil": "python-dateutil",
    }
    stdlib = set(sys.stdlib_module_names)

    third_party: set[str] = set()
    for path in RUNTIME.rglob("*.py"):
        for node in ast.walk(ast.parse(path.read_text(), filename=str(path))):
            if isinstance(node, ast.Import):
                mods = [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                mods = [node.module or ""] if node.level == 0 else []
            else:
                continue
            for mod in mods:
                top = mod.split(".")[0].lower()
                if top and top not in stdlib and top != "rainalert":
                    third_party.add(normalise(aliases.get(top, top)))

    missing = sorted(
        name
        for name in third_party
        # google-cloud-storage is imported lazily inside the GCS adapters and is an optional extra.
        if name not in names and name not in {"google", "wradlib"}
    )
    assert missing == [], f"imported but not declared in pyproject: {missing}"
