"""alerting: evaluations, states, events, notifications

Revision ID: 0d07df25ad95
Revises: e2da8fe2ac90
Create Date: 2026-09-17 05:48:51.615581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d07df25ad95'
down_revision: Union[str, Sequence[str], None] = 'e2da8fe2ac90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_states',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('unknown', 'dry', 'warned', 'raining', name='alert_state'), nullable=False),
    sa.Column('state_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dry_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_hit_cycles', sa.Integer(), nullable=False),
    sa.Column('current_event_id', sa.BigInteger(), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('now_wet', sa.Boolean(), nullable=False),
    sa.Column('first_hit_lead_minutes', sa.Integer(), nullable=True),
    sa.Column('max_rate_by_lead', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('missing_fraction', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('state_before', sa.Enum('unknown', 'dry', 'warned', 'raining', name='alert_state'), nullable=False),
    sa.Column('state_after', sa.Enum('unknown', 'dry', 'warned', 'raining', name='alert_state'), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['radar_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('evaluations_by_sub_time', 'evaluations', ['subscription_id', 'evaluated_at'], unique=False)
    op.create_index('evaluations_purge', 'evaluations', ['evaluated_at'], unique=False)
    op.create_index('uq_evaluation', 'evaluations', ['subscription_id', 'cycle_id'], unique=True)
    op.create_table('rain_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peak_mm_5min', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rain_events_subscription_id'), 'rain_events', ['subscription_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=256), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['rain_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_subscription_id'), 'notifications', ['subscription_id'], unique=False)
    op.create_index('notifications_pending', 'notifications', ['status', 'queued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('notifications_pending', table_name='notifications')
    op.drop_index(op.f('ix_notifications_subscription_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_rain_events_subscription_id'), table_name='rain_events')
    op.drop_table('rain_events')
    op.drop_index('uq_evaluation', table_name='evaluations')
    op.drop_index('evaluations_purge', table_name='evaluations')
    op.drop_index('evaluations_by_sub_time', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_table('alert_states')
    # ### end Alembic commands ###
