"""subscriptions, tokens, rate limit hits

Revision ID: e2da8fe2ac90
Revises: 
Create Date: 2026-09-16 20:56:47.418444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2da8fe2ac90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_cycles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nominal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('last_modified', sa.String(length=64), nullable=True),
    sa.Column('sha256', sa.LargeBinary(length=32), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'partial', 'rejected', 'failed', name='cycle_status'), nullable=False),
    sa.Column('archive_uri', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radar_cycles_nominal_time'), 'radar_cycles', ['nominal_time'], unique=True)
    op.create_table('rate_limit_hits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_hits_bucket'), 'rate_limit_hits', ['bucket'], unique=False)
    op.create_index(op.f('ix_rate_limit_hits_occurred_at'), 'rate_limit_hits', ['occurred_at'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_ip_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('consent_user_agent', sa.String(length=256), nullable=True),
    sa.Column('consent_text_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email_hash'), 'subscribers', ['email_hash'], unique=True)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscriber_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('confirm', 'api', 'unsubscribe', name='token_purpose'), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_subscriber_id'), 'auth_tokens', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscriber_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'paused', 'unhealthy', name='subscription_status'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grid_row', sa.Integer(), nullable=True),
    sa.Column('grid_col', sa.Integer(), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('threshold_mm_5min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lead_time_minutes', sa.Integer(), nullable=False),
    sa.Column('min_gap_minutes', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('health_note', sa.Text(), nullable=True),
    sa.CheckConstraint('lat BETWEEN 47.0 AND 56.0', name='lat_in_germany'),
    sa.CheckConstraint('lead_time_minutes BETWEEN 5 AND 120', name='lead_sane'),
    sa.CheckConstraint('lon BETWEEN 5.0 AND 16.0', name='lon_in_germany'),
    sa.CheckConstraint('min_gap_minutes >= 0', name='min_gap_sane'),
    sa.CheckConstraint('radius_m BETWEEN 0 AND 20000', name='radius_sane'),
    sa.CheckConstraint('threshold_mm_5min > 0', name='threshold_positive'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_subscriber_id'), 'subscriptions', ['subscriber_id'], unique=False)
    op.create_index('one_subscription_per_subscriber', 'subscriptions', ['subscriber_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_subscription_per_subscriber', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subscriber_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_subscriber_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_subscribers_email_hash'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_rate_limit_hits_occurred_at'), table_name='rate_limit_hits')
    op.drop_index(op.f('ix_rate_limit_hits_bucket'), table_name='rate_limit_hits')
    op.drop_table('rate_limit_hits')
    op.drop_index(op.f('ix_radar_cycles_nominal_time'), table_name='radar_cycles')
    op.drop_table('radar_cycles')
    # ### end Alembic commands ###
